# Generated by Django 3.0.7 on 2021-01-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='pessoal',
            new_name='pessoa',
        ),
    ]
